### ISSUE TITLE
Describe how initial data import works

### ISSUE THREAD

**Issue by ryguyrg** [neo4j-contrib/neo4j_doc_manager#14]
I already have data in Mongo.  How do I move that initial data over to Neo4j before I then handle subsequent "live" data updates/inserts/etc

**Comment by ryguyrg** [comment]
Note: this doc discusses how it works:
https://github.com/neo4j-contrib/neo4j_doc_manager

That said, I didn't see how existing data import works.

**Comment by johnymontana** [comment]
I removed the reference to this from the README as this functionality did not seem to be supported at this point. Looking at comments from @llvtt in issue #21 perhaps the reason this didn't work is the unimplemented `bulk_upsert` method.

**Comment by johnymontana** [comment]
`bulk_upsert` has been implemented and initial data import functionality is described in the docs [here](https://github.com/neo4j-contrib/neo4j_doc_manager/blob/master/docs/neo4j_doc_manager_doc.adoc#223-bulk-upsert)
