### ISSUE TITLE
Ensure character translation for valid node/property names/etc

### ISSUE THREAD

**Issue by ryguyrg** [neo4j-contrib/neo4j_doc_manager#15]
Looks like dashes are valid for mongo document collection names, but invalid for Neo4j?

InvalidSyntax: Invalid input '-': expected an identifier character, whitespace or ')' (line 1, column 33 (offset: 32))
"CREATE CONSTRAINT ON (d:employee-territories) ASSERT d._id IS UNIQUE"

Source: tried running mongo-import.sh from:
https://github.com/tmcnab/northwind-mongo

**Comment by jexp** [comment]
We have to use backticks around all identifiers that we don't control

like 

```
CREATE CONSTRAINT ON (d:`employee-territories`) ASSERT d._id IS UNIQUE
```
same goes for property names etc.

**Comment by ryguyrg** [comment]
Right now, she's doing parameter substitution.  Shouldn't py2neo and/or the Neo4j protocol automatically handle this?

**Comment by jexp** [comment]
No parametrization for identifiers in neither.

**Comment by hannelita** [comment]
PR https://github.com/neo4j-contrib/neo4j_doc_manager/pull/40 fixes this point. Let me know if you have any further considerations. Thanks.
