### ISSUE TITLE
Specify mongo_connector as dependency in setup.py

### ISSUE THREAD

**Issue by johnymontana** [neo4j-contrib/neo4j_doc_manager#16]
Current installation process as described in README is to install mongo-connector with `pip` before installing neo4j_doc_manager. Is there a reason `mongo-connector` is not included as a dependency in `setup.py` `install_requires`? This would remove the requirement to first install mongo-connector with pip.

**Comment by ryguyrg** [comment]
Also probably py2neo and all other imports?

**Comment by hannelita** [comment]
Resolved; pypi package is working
