### ISSUE TITLE
Implement bulk indexing or leave it out

### ISSUE THREAD

**Issue by llvtt** [neo4j-contrib/neo4j_doc_manager#21]
The [`bulk_upsert`](https://github.com/neo4j-contrib/neo4j_doc_manager/blob/master/mongo_connector/doc_managers/neo4j_doc_manager.py#L72-L74) method doesn't currently do anything. If the DocManager doesn't support bulk inserts, then this method should be left unimplemented, so that the [default `bulk_upsert`](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/doc_managers/doc_manager_base.py#L93-L99) method will be used (this just does upserts serially). This method is always called during a collection dump, so I suspect that currently this DocManager won't properly synchronize any documents already in MongoDB (before tailing the oplog) correctly, though I haven't actually run this code.

Maybe this method is still a WIP?

There are also a few other methods that should be implemented, but aren't yet (maybe they're all WIPs):
- search
- commit
- get_last_doc

https://github.com/neo4j-contrib/neo4j_doc_manager/blob/master/mongo_connector/doc_managers/neo4j_doc_manager.py#L100-L108

Sorry to annoy you if you're already working on implementing these; just don't want this to slip through the cracks!

**Comment by ryguyrg** [comment]
@llvtt definitely not annoying.  very helpful indeed!  /cc @hannelita

**Comment by hannelita** [comment]
Hi!
Thanks for these points. Bulk Upsert was recently implemented here https://github.com/neo4j-contrib/neo4j_doc_manager/pull/38 
Let me know if you have further considerations.
