### ISSUE TITLE
Implement run_auto_commit

### ISSUE THREAD

**Issue by llvtt** [neo4j-contrib/neo4j_doc_manager#22]
The DocManager makes a call to [`self.run_auto_commit`](https://github.com/neo4j-contrib/neo4j_doc_manager/blob/master/mongo_connector/doc_managers/neo4j_doc_manager.py#L41), but this method is not defined.

**Comment by hannelita** [comment]
Good point! Thanks. We will only use the default value (None) for while. It's already fixed on master branch.
