### ISSUE TITLE
Allow attributes to be `$unset`/assigned directly in updates

### ISSUE THREAD

**Issue by llvtt** [neo4j-contrib/neo4j_doc_manager#23]
In a MongoDB update specification, there can be three different ways to update a field within a document:

1. Using the `$set` operator, e.g. `{"$set": {"field": "value"}}` (sets "field" to "value")
2. Using the `$unset` operator, e.g. `{"$unset": "field"}` (causes this field to be removed)
3. Direct assignment, e.g. `{"field": "value"}` (basically the same as (1) above).

It looks like the [`update` method](https://github.com/neo4j-contrib/neo4j_doc_manager/blob/master/mongo_connector/doc_managers/neo4j_doc_manager.py#L78) might only handle the first case.

Honestly, I haven't worked with neo4j before, so I don't know what the syntax is for updating a document; maybe there isn't even a notion of un-setting attributes. If that's the case, then ignore this.

Otherwise, you might want to look into grabbing values from `$unset` and checking for direct assignments contained in update specs pulled from the MongoDB oplog. This can get a bit hairy to do correctly, so most DocManagers packaged with mongo-connector use the [`apply_update`](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/doc_managers/doc_manager_base.py#L23-L91) method for this purpose (this method assumes the document is retrieved from the remote end as a Python dict). Here's what Solr does (document is retrieved from the remote end as a flattened Python dict): https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/doc_managers/solr_doc_manager.py#L191-L222

Another strategy is to grab the latest version of the document from MongoDB, using its `_id`. This doesn't really have the same affect as applying the update, since the current state of the document in MongoDB may not be the expected state of the document given how much oplog has been applied. But perhaps this can be considered an approximation that's "good enough."

You can borrow some test cases from here to inspect what this DocManager does in various scenarios with updates: https://github.com/mongodb-labs/mongo-connector/blob/master/tests/test_elastic.py#L164-L205

**Comment by hannelita** [comment]
We have just pushed some updates to this point to master :)
