### ISSUE TITLE
make the databases / list of collections configurable that are replicated

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j_doc_manager#25]
currently all databases of an instance are transferred, it would be very sensible to allow / configure which databases or sets of collections are replicated

by @JoergM

**Comment by johnymontana** [comment]
This is now supported and documented [here](https://github.com/neo4j-contrib/neo4j_doc_manager/blob/master/docs/neo4j_doc_manager_doc.adoc#23-customising-the-data-to-be-imported)
