### ISSUE TITLE
Logging to mongo-connector.log. waits infinitely....................................

### ISSUE THREAD

**Issue by Vanaja1505** [neo4j-contrib/neo4j_doc_manager#58]
Hi,
I have installed neo4j doc manager as per the document. When I try to sync my mongodb data using the below command it waits infinitely...

> Python35-32>mongo-connector -m l
> ocalhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
> Logging to mongo-connector.log.

The content of mongo-connector.log is as follows:

> 2016-02-26 19:10:11,809 [ERROR] mongo_connector.doc_managers.neo4j_doc_manager:70 - Bulk

The content of oplog.timestamp is as follows:

> ["Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='myDevReplSet'), 'local'), 'oplog.rs')", 6255589333701492738]

Please help ASAP..

**Comment by johnymontana** [comment]
Is there any other information in the log? Was any data inserted into Neo4j? 

mongo-connector will run continuously and after the initial bulk insert will continue to listen for any other updates to mongo so you shouldn't expect the script to exit unless explicitly stopped.

**Comment by Vanaja1505** [comment]
No other information available in the log. Neo4j has the sample Movie database initially. And mongodb has talks collection in it. I am expecting Neo4j to show the talks graph in addition to the already available Movie graph.

**Comment by Vanaja1505** [comment]
I need an immediate response.....

**Comment by johnymontana** [comment]
I don't see anything indicative of the problem in the log.

Do you have authentication enabled in Neo4j? If so did you set `NEO4J_AUTH` environment variable? I would expect a different error if that's the issue, however.

Also try removing the `oplog.timestamp` file and restarting mongo-connector to try the import again.

**Comment by Vanaja1505** [comment]
Nothing went wrong with my installation.

The data added to mongodb after the mongo-connector service started is automatically displayed in Neo4j. The data which are available in Mongodb before the service is started cannot be loaded into Neo4j.
