### ISSUE TITLE
Could not import mongo_connector.doc_managers.neo4j_doc_manager.

### ISSUE THREAD

**Issue by joelmatiassilva** [neo4j-contrib/neo4j_doc_manager#60]
Hi,
when I run the following command:
mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager

displays the following error:
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 9, in <module>
    load_entry_point('mongo-connector==2.3', 'console_scripts', 'mongo-connector')()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/connector.py", line 1041, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/config.py", line 118, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/connector.py", line 824, in apply_doc_managers
    module = import_dm_by_name(dm['docManager'])
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/connector.py", line 814, in import_dm_by_name
    "vailable doc managers." % full_name)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.neo4j_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers.

![software](https://cloud.githubusercontent.com/assets/978091/15347845/7e66f530-1c9b-11e6-8293-6b8c69037f39.png)
![error](https://cloud.githubusercontent.com/assets/978091/15347846/9073f944-1c9b-11e6-9ad2-e00d1ae0f0f8.png)

**Comment by johnymontana** [comment]
This appears to be an error caused by failing to pin the py2neo dependency to a specific version. This project was written using py2neo 2.0.7 but failed to pin that version, as py2neo 3.0 is  now being pulled in a few things are breaking.

We will push an update for 3.0 soon, in the meantime you can get around this by uninstalling py2neo and installing version 2.0.7:

```
lyonwj@lyonwjs-MacBook-Pro-2 ~/n/mongo_demo> pip uninstall py2neo
Uninstalling py2neo-3
...
lyonwj@lyonwjs-MacBook-Pro-2 ~/n/mongo_demo> pip install py2neo==2.0.7
Collecting py2neo==2.0.7
  Downloading py2neo-2.0.7.tar.gz (251kB)
    100% |████████████████████████████████| 256kB 2.6MB/s
Installing collected packages: py2neo
  Running setup.py install for py2neo ... done
Successfully installed py2neo-2.0.7
lyonwj@lyonwjs-MacBook-Pro-2 ~/n/mongo_demo>
mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
Logging to mongo-connector.log.
```

**Comment by johnymontana** [comment]
This appears to be an error caused by failing to pin the py2neo dependency to a specific version. This project was written using py2neo 2.0.7 but failed to pin that version, as py2neo 3.0 is  now being pulled in a few things are breaking.

We will push an update for 3.0 soon, in the meantime you can get around this by uninstalling py2neo and installing version 2.0.7:


    lyonwj@lyonwjs-MacBook-Pro-2 ~/n/mongo_demo> pip uninstall py2neo
    Uninstalling py2neo-3
    ...
    lyonwj@lyonwjs-MacBook-Pro-2 ~/n/mongo_demo> pip install py2neo==2.0.7
    Collecting py2neo==2.0.7
      Downloading py2neo-2.0.7.tar.gz (251kB)
        100% |████████████████████████████████| 256kB 2.6MB/s
    Installing collected packages: py2neo
      Running setup.py install for py2neo ... done
    Successfully installed py2neo-2.0.7
    lyonwj@lyonwjs-MacBook-Pro-2 ~/n/mongo_demo>
    mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
    Logging to mongo-connector.log.

**Comment by akarsh** [comment]
I had the similar issue @joelmatiassilva 
your solution solved for macOS
but it uninstalled
`Uninstalling py2neo-4.0.0b2:`

**Comment by johnda98** [comment]
does 5.0b1 work ok ? or is it just 2.0.7 ?  I had 2.0.8 and had similar probs w py2neo   its 2020 now Oct !

**Comment by pedromsilva99** [comment]
pyneo 2.0.7 is not available anymore, does any of the new versions work with neo4j_doc_manager?
