### ISSUE TITLE
neo_doc_manager fails with py2neo 1.6

### ISSUE THREAD

**Issue by Hassanbenlebsir** [neo4j-contrib/neo4j_doc_manager#64]
I have python 2,6 and i can't upgrade it because of my work environment i must stay on 2,6
and i'm trying to work with neo-doc-manager and this requeres installing py2neo.
on pyhton 2,6 i can't install the latest version of py2neo so i installed the py2neo 1,6

**and when i try to make a connection:**
mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager

**i get this error:** 
`    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6AsNjN/py2neo/setup.py", line 29, in <module>
        from py2neo import **author**, **email**, **license**, **package**, **version**
      File "py2neo/**init**.py", line 27, in <module>
        from py2neo.core import *
      File "py2neo/core.py", line 1414
        new_inst.__stale.update({"labels", "properties"})
                                         ^
    SyntaxError: invalid syntax

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6AsNjN/py2ne`

so is there a solution for this

**Comment by johnymontana** [comment]
Unfortunately neo4j_doc_manager requires at least py2neo 2.0.8 which does not support Python 2.6. To use neo4j_doc_manager you'll need to use at least Python 2.7, preferably Python 3.4+. I would suggest using a [virualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/) in your development environment to use a more recent version of Python.

**Comment by Hassanbenlebsir** [comment]
Thank you for you fast reply,

i upgraded python and now everything is up and running.
i can do inserts from mongo to neo4j.

i have a question before that i'll explain what i'm doing.
i'm on 2 virtual machines i have installed neo4j on one vm and mongo on the other.
and i'm doing the mongo-connector fro the machine to the other and that's fine.

but i how can i export all the DB that i already had in mongo to neo4j.
